services:
  - type: web
    name: nirikshan-sih-102
    runtime: docker
    repo: https://github.com/amanrathore628/102final
    branch: main
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: USE_SQLITE_FALLBACK
        value: "true"
